name: ci

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always
  STATIC_BUILD_TARGET: x86_64-unknown-linux-musl

jobs:
  check:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: cargo/check
        run: cargo check
      - name: cargo/test
        run: cargo test
      - name: cargo/clippy
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cargo clippy
  release:
    # runs on tags only
    if: startsWith(github.ref, 'refs/tags/')
    needs: [check]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            file: zr
            from-file: ./target/release/zr
            to-file: zr-linux.tar.gz
            args: --best --lzma
            strip: true
          - os: macos-latest
            file: zr
            from-file: ./target/release/zr
            to-file: zr-macos.tar.gz
            args: --best
            strip: true
          - os: windows-latest
            file: zr.exe
            from-file: ./target/release/zr.exe
            to-file: zr-windows.zip
            args: -9
            strip: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: cargo/build
        run: cargo build --release
      - name: upx
        uses: svenstaro/upx-action@v2
        with:
          file: ${{ matrix.from-file }}
          args: ${{ matrix.args }}
          strip: ${{ matrix.strip }}
      - name: compression/tar
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          cd target/release
          tar czf ${{ matrix.to-file }} ${{ matrix.file }}
          mv ${{ matrix.to-file }} ../..
      - name: compression/zip
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd target/release
          7z a ${{ matrix.to-file }} ${{ matrix.file }}
          mv ${{ matrix.to-file }} ../..
      - name: release-assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ matrix.to-file }}
            target/bench.tar.gz